# VectorDB hyperparameters
VECTOR_DB_DISEASE_ENTITY_PATH : 'data/disease_with_relation_to_genes.pickle'
VECTOR_DB_PATH : 'data/vectorDB/disease_nodes_db'
VECTOR_DB_CHUNK_SIZE : 650
VECTOR_DB_CHUNK_OVERLAP : 200
VECTOR_DB_BATCH_SIZE : 200
VECTOR_DB_SENTENCE_EMBEDDING_MODEL : 'sentence-transformers/all-MiniLM-L6-v2'

# Path for context file from SPOKE KG
NODE_CONTEXT_PATH : 'data/context_of_disease_which_has_relation_to_genes.csv'

# SPOKE-API params
BASE_URI : 'https://spoke.rbvi.ucsf.edu'
cutoff_Compound_max_phase : 3
cutoff_Protein_source : ['SwissProt']
cutoff_DaG_diseases_sources : ['knowledge', 'experiments']
cutoff_DaG_textmining : 3
cutoff_CtD_phase : 3
cutoff_PiP_confidence : 0.7
cutoff_ACTeG_level : ['Low', 'Medium', 'High']
depth : 1
cutoff_DpL_average_prevalence : 0.001

# KG-RAG hyperparameters
GPT_CONFIG_FILE : '.gpt_config.env'
GPT_API_TYPE : 'open_ai'
LLM_TEMPERATURE : 0
CONTEXT_VOLUME : 600
QUESTION_VS_CONTEXT_SIMILARITY_PERCENTILE_THRESHOLD : 70
QUESTION_VS_CONTEXT_MINIMUM_SIMILARITY : 0.4
SENTENCE_EMBEDDING_MODEL_FOR_NODE_RETRIEVAL : 'sentence-transformers/all-MiniLM-L6-v2'
SENTENCE_EMBEDDING_MODEL_FOR_CONTEXT_RETRIEVAL : 'pritamdeka/S-PubMedBert-MS-MARCO'
